Repository YAPP-Github/TnT-Server, pull requests merged in 2025-02, with the labels that each got.

#35 [TNT - 162] feat: 회원 탈퇴 기능 구현
  src/main/java/com/tnt/application/member/MemberService.java
  src/main/java/com/tnt/application/member/SignUpService.java
  src/main/java/com/tnt/application/member/WithdrawService.java
  src/main/java/com/tnt/application/pt/PtService.java
  src/main/java/com/tnt/application/s3/S3Service.java
  src/main/java/com/tnt/application/trainee/PtGoalService.java
  src/main/java/com/tnt/application/trainee/TraineeService.java
  src/main/java/com/tnt/application/trainer/TrainerService.java
  src/main/java/com/tnt/common/error/handler/GlobalExceptionHandler.java
  src/main/java/com/tnt/common/error/model/ErrorMessage.java
  src/main/java/com/tnt/domain/member/Member.java
  src/main/java/com/tnt/domain/pt/PtLesson.java
  src/main/java/com/tnt/domain/pt/PtTrainerTrainee.java
  src/main/java/com/tnt/domain/trainee/PtGoal.java
  src/main/java/com/tnt/domain/trainee/Trainee.java
  src/main/java/com/tnt/domain/trainer/Trainer.java
  src/main/java/com/tnt/dto/member/WithdrawDto.java
  src/main/java/com/tnt/dto/member/request/WithdrawRequest.java
  src/main/java/com/tnt/dto/trainer/request/ConnectWithTrainerRequest.java
  src/main/java/com/tnt/gateway/controller/AuthenticationController.java
  src/main/java/com/tnt/gateway/dto/AppleAuthTokenInfo.java
  src/main/java/com/tnt/gateway/dto/request/OAuthLoginRequest.java
  src/main/java/com/tnt/gateway/dto/response/OAuthLoginResponse.java
  src/main/java/com/tnt/gateway/service/OAuthService.java
  src/main/java/com/tnt/infrastructure/mysql/repository/pt/PtGoalRepository.java
  src/main/java/com/tnt/infrastructure/mysql/repository/pt/PtLessonRepository.java
  src/main/java/com/tnt/infrastructure/mysql/repository/pt/PtTrainerTraineeRepository.java
  src/main/java/com/tnt/infrastructure/mysql/repository/trainee/TraineeRepository.java
  src/main/java/com/tnt/infrastructure/s3/S3Adapter.java
  src/main/java/com/tnt/presentation/member/MemberController.java
  src/main/java/com/tnt/presentation/trainee/TraineeController.java
  src/main/java/com/tnt/presentation/trainer/TrainerController.java
  src/test/java/com/tnt/application/member/MemberServiceTest.java
  src/test/java/com/tnt/application/member/OAuthServiceTest.java
  src/test/java/com/tnt/application/member/SignUpServiceTest.java
  src/test/java/com/tnt/application/member/WithdrawServiceTest.java
  src/test/java/com/tnt/application/pt/PtGoalServiceTest.java
  src/test/java/com/tnt/application/pt/PtServiceTest.java
  src/test/java/com/tnt/domain/member/MemberTest.java
  src/test/java/com/tnt/fixture/MemberFixture.java
  src/test/java/com/tnt/fixture/PtLessonsFixture.java
  src/test/java/com/tnt/gateway/controller/AuthenticationControllerTest.java
  src/test/java/com/tnt/gateway/service/OAuthServiceTest.java
  src/test/java/com/tnt/presentation/member/MemberControllerTest.java
  src/test/java/com/tnt/presentation/trainer/TrainerControllerTest.java
Labels: ✨ feature, ✅ test, ♻ refactor

#39 [#38] hotfix: 탈퇴 후 재가입 안되는 현상
  src/main/java/com/tnt/application/member/MemberService.java
  src/main/java/com/tnt/application/member/SignUpService.java
  src/main/java/com/tnt/application/pt/PtService.java
  src/main/java/com/tnt/application/trainee/PtGoalService.java
  src/main/java/com/tnt/application/trainee/TraineeService.java
  src/main/java/com/tnt/application/trainer/TrainerService.java
  src/main/java/com/tnt/domain/member/Member.java
  src/main/java/com/tnt/dto/member/MemberProjection.java
  src/main/java/com/tnt/gateway/controller/AuthenticationController.java
  src/main/java/com/tnt/gateway/dto/response/CheckSessionResponse.java
  src/main/java/com/tnt/infrastructure/mysql/repository/member/MemberSearchRepository.java
  src/test/java/com/tnt/application/member/MemberServiceTest.java
  src/test/java/com/tnt/gateway/controller/AuthenticationControllerTest.java
Labels: 🐞 bugfix

#40 [TNT-204] feat: 회원 조회 기능 구현
  src/main/java/com/tnt/application/member/MemberService.java
  src/main/java/com/tnt/application/member/SignUpService.java
  src/main/java/com/tnt/dto/member/MemberProjection.java
  src/main/java/com/tnt/dto/member/request/SignUpRequest.java
  src/main/java/com/tnt/dto/member/response/GetMemberInfoResponse.java
  src/main/java/com/tnt/infrastructure/mysql/repository/member/MemberSearchRepository.java
  src/main/java/com/tnt/presentation/member/MemberController.java
  src/test/java/com/tnt/application/member/MemberServiceTest.java
  src/test/java/com/tnt/fixture/PtGoalsFixture.java
  src/test/java/com/tnt/presentation/member/MemberControllerTest.java
Labels: ✨ feature

#45 [TNT-193] 트레이너 달력 표시에 필요한 데이터 요청 API 구현
  build.gradle
  src/main/java/com/tnt/application/pt/PtService.java
  src/main/java/com/tnt/application/trainer/TrainerService.java
  src/main/java/com/tnt/domain/member/Member.java
  src/main/java/com/tnt/dto/trainer/response/ConnectWithTraineeResponse.java
  src/main/java/com/tnt/dto/trainer/response/GetCalendarPtLessonCountResponse.java
  src/main/java/com/tnt/dto/trainer/response/InvitationCodeVerifyResponse.java
  src/main/java/com/tnt/infrastructure/mysql/repository/pt/PtLessonSearchRepository.java
  src/main/java/com/tnt/infrastructure/mysql/repository/trainer/TrainerRepository.java
  src/main/java/com/tnt/presentation/trainer/TrainerController.java
  src/test/java/com/tnt/application/member/SignUpServiceTest.java
  src/test/java/com/tnt/application/pt/PtServiceTest.java
  src/test/java/com/tnt/application/trainer/TrainerServiceTest.java
  src/test/java/com/tnt/presentation/trainer/TrainerControllerTest.java
Labels: ✨ feature

#49 [#48] refactor: 프론트에 에러 출력 세분화
  build.gradle
  src/main/java/com/tnt/common/error/handler/GlobalExceptionHandler.java
  src/main/java/com/tnt/gateway/config/SecurityConfig.java
  src/main/java/com/tnt/gateway/filter/ServletExceptionFilter.java
  src/main/java/com/tnt/gateway/filter/SessionAuthenticationFilter.java
  src/main/java/com/tnt/gateway/service/SessionService.java
  src/test/java/com/tnt/gateway/filter/ServletExceptionFilterTest.java
  src/test/java/com/tnt/gateway/filter/SessionAuthenticationFilterTest.java
  src/test/java/com/tnt/gateway/service/SessionServiceTest.java
Labels: ♻ refactor

#46 [TNT-212] refactor: 회원 조회 API 응답 데이터 추가
  src/main/java/com/tnt/application/member/MemberService.java
  src/main/java/com/tnt/common/constant/ProfileConstant.java
  src/main/java/com/tnt/dto/member/MemberProjection.java
  src/main/java/com/tnt/dto/member/response/GetMemberInfoResponse.java
  src/main/java/com/tnt/infrastructure/mysql/repository/member/MemberSearchRepository.java
  src/test/java/com/tnt/fixture/MemberFixture.java
  src/test/java/com/tnt/fixture/PtTrainerTraineeFixture.java
  src/test/java/com/tnt/presentation/member/MemberControllerTest.java
Labels: ♻ refactor

#51 [TNT-223] feat: 트레이너 - PT 수업 추가 기능 구현
  src/main/java/com/tnt/application/pt/PtService.java
  src/main/java/com/tnt/application/trainer/TrainerService.java
  src/main/java/com/tnt/common/error/handler/GlobalExceptionHandler.java
  src/main/java/com/tnt/common/error/model/ErrorMessage.java
  src/main/java/com/tnt/dto/trainer/request/CreatePtLessonRequest.java
  src/main/java/com/tnt/dto/trainer/response/GetActiveTraineesResponse.java
  src/main/java/com/tnt/infrastructure/mysql/repository/pt/PtLessonSearchRepository.java
  src/main/java/com/tnt/infrastructure/mysql/repository/pt/PtTrainerTraineeSearchRepository.java
  src/main/java/com/tnt/infrastructure/mysql/repository/trainer/TrainerRepository.java
  src/main/java/com/tnt/presentation/trainer/TrainerController.java
  src/test/java/com/tnt/application/member/WithdrawServiceTest.java
  src/test/java/com/tnt/application/pt/PtServiceTest.java
  src/test/java/com/tnt/domain/pt/PtLessonTest.java
  src/test/java/com/tnt/fixture/MemberFixture.java
  src/test/java/com/tnt/fixture/PtTrainerTraineeFixture.java
  src/test/java/com/tnt/fixture/TraineeFixture.java
  src/test/java/com/tnt/presentation/member/MemberControllerTest.java
  src/test/java/com/tnt/presentation/trainer/TrainerControllerTest.java
Labels: ✨ feature

#54 [TNT-226] feat: 트레이너 - PT 수업 완료 처리 기능 구현
  .github/workflows/cd-dev.yml
  infra/Dockerfile
  src/main/java/com/tnt/application/member/MemberService.java
  src/main/java/com/tnt/application/member/WithdrawService.java
  src/main/java/com/tnt/application/pt/PtService.java
  src/main/java/com/tnt/common/error/model/ErrorMessage.java
  src/main/java/com/tnt/dto/member/response/GetMemberInfoResponse.java
  src/main/java/com/tnt/dto/trainer/response/ConnectWithTraineeResponse.java
  src/main/java/com/tnt/infrastructure/mysql/repository/pt/PtLessonRepository.java
  src/main/java/com/tnt/infrastructure/mysql/repository/pt/PtTrainerTraineeRepository.java
  src/main/java/com/tnt/presentation/member/MemberController.java
  src/main/java/com/tnt/presentation/trainer/TrainerController.java
  src/test/java/com/tnt/application/member/WithdrawServiceTest.java
  src/test/java/com/tnt/presentation/member/MemberControllerTest.java
  src/test/java/com/tnt/presentation/trainer/TrainerControllerTest.java
Labels: ✨ feature, ♻ refactor

#57 [TNT-217] feat: 트레이니 - 식단 등록 기능 구현
  src/main/java/com/tnt/application/member/SignUpService.java
  src/main/java/com/tnt/application/pt/PtService.java
  src/main/java/com/tnt/application/s3/S3Service.java
  src/main/java/com/tnt/application/trainee/DietService.java
  src/main/java/com/tnt/common/constant/ImageConstant.java
  src/main/java/com/tnt/common/error/model/ErrorMessage.java
  src/main/java/com/tnt/domain/trainee/Diet.java
  src/main/java/com/tnt/domain/trainee/DietType.java
  src/main/java/com/tnt/dto/trainee/request/ConnectWithTrainerRequest.java
  src/main/java/com/tnt/dto/trainee/request/CreateDietRequest.java
  src/main/java/com/tnt/dto/trainer/response/GetActiveTraineesResponse.java
  src/main/java/com/tnt/infrastructure/mysql/repository/member/MemberSearchRepository.java
  src/main/java/com/tnt/infrastructure/mysql/repository/trainee/DietRepository.java
  src/main/java/com/tnt/presentation/trainee/TraineeController.java
  src/test/java/com/tnt/application/member/SignUpServiceTest.java
  src/test/java/com/tnt/application/pt/PtServiceTest.java
  src/test/java/com/tnt/application/s3/S3ServiceTest.java
  src/test/java/com/tnt/presentation/member/MemberControllerTest.java
  src/test/java/com/tnt/presentation/trainee/TraineeControllerTest.java
  src/test/java/com/tnt/presentation/trainer/TrainerControllerTest.java
Labels: ✨ feature, ✅ test

#58 [TNT-228] feat: 트레이니 홈 화면 달력 - PT 수업 있는 날짜 반환 API 구현
  src/main/java/com/tnt/application/pt/PtService.java
  src/main/java/com/tnt/dto/trainee/response/ConnectWithTrainerResponse.java
  src/main/java/com/tnt/dto/trainee/response/GetTraineeCalendarPtLessonCountResponse.java
  src/main/java/com/tnt/dto/trainer/ConnectWithTrainerDto.java
  src/main/java/com/tnt/infrastructure/mysql/repository/pt/PtLessonSearchRepository.java
  src/main/java/com/tnt/presentation/trainee/TraineeController.java
  src/test/java/com/tnt/application/member/WithdrawServiceTest.java
  src/test/java/com/tnt/application/pt/PtServiceTest.java
  src/test/java/com/tnt/fixture/PtLessonsFixture.java
  src/test/java/com/tnt/presentation/trainee/TraineeControllerTest.java
Labels: ✨ feature

#60 [TNT-218] feat: 트레이니 특정 식단, 홈 기록 리스트 조회 기능 구현
  src/main/java/com/tnt/application/member/MemberService.java
  src/main/java/com/tnt/application/pt/PtService.java
  src/main/java/com/tnt/application/trainee/DietService.java
  src/main/java/com/tnt/application/trainee/TraineeService.java
  src/main/java/com/tnt/common/error/model/ErrorMessage.java
  src/main/java/com/tnt/domain/pt/PtLesson.java
  src/main/java/com/tnt/domain/trainee/Diet.java
  src/main/java/com/tnt/domain/trainee/Trainee.java
  src/main/java/com/tnt/dto/member/MemberProjection.java
  src/main/java/com/tnt/dto/member/response/GetMemberInfoResponse.java
  src/main/java/com/tnt/dto/trainee/TraineeProjection.java
  src/main/java/com/tnt/dto/trainee/response/CreateDietResponse.java
  src/main/java/com/tnt/dto/trainee/response/GetDietResponse.java
  src/main/java/com/tnt/dto/trainee/response/GetTraineeDailyRecordsResponse.java
  src/main/java/com/tnt/dto/trainer/response/GetActiveTraineesResponse.java
  src/main/java/com/tnt/infrastructure/mysql/repository/pt/PtLessonRepository.java
  src/main/java/com/tnt/infrastructure/mysql/repository/pt/PtLessonSearchRepository.java
  src/main/java/com/tnt/infrastructure/mysql/repository/pt/PtTrainerTraineeSearchRepository.java
  src/main/java/com/tnt/infrastructure/mysql/repository/trainee/DietRepository.java
  src/main/java/com/tnt/infrastructure/mysql/repository/trainee/DietSearchRepository.java
  src/main/java/com/tnt/infrastructure/mysql/repository/trainee/TraineeRepository.java
  src/main/java/com/tnt/infrastructure/mysql/repository/trainee/TraineeSearchRepository.java
  src/main/java/com/tnt/infrastructure/mysql/repository/trainer/TrainerSearchRepository.java
  src/main/java/com/tnt/presentation/trainee/TraineeController.java
  src/test/java/com/tnt/application/member/WithdrawServiceTest.java
  src/test/java/com/tnt/application/pt/PtServiceTest.java
  src/test/java/com/tnt/application/s3/S3ServiceTest.java
  src/test/java/com/tnt/domain/pt/PtLessonTest.java
  src/test/java/com/tnt/fixture/DietFixture.java
  src/test/java/com/tnt/fixture/PtLessonsFixture.java
  src/test/java/com/tnt/fixture/PtTrainerTraineeFixture.java
  src/test/java/com/tnt/presentation/member/MemberControllerTest.java
  src/test/java/com/tnt/presentation/trainee/TraineeControllerTest.java
  src/test/java/com/tnt/presentation/trainer/TrainerControllerTest.java
Labels: ✨ feature, ✅ test, ♻ refactor

#62 [TNT-246] refactor: 트레이니 특정 날짜 기록 조회 API
  src/main/java/com/tnt/application/pt/PtService.java
  src/main/java/com/tnt/application/trainee/DietService.java
  src/main/java/com/tnt/dto/trainee/response/GetTraineeCalendarPtLessonCountResponse.java
  src/main/java/com/tnt/dto/trainee/response/GetTraineeDailyRecordsResponse.java
  src/main/java/com/tnt/infrastructure/mysql/repository/pt/PtLessonSearchRepository.java
  src/main/java/com/tnt/infrastructure/mysql/repository/trainee/DietSearchRepository.java
  src/main/java/com/tnt/presentation/trainee/TraineeController.java
  src/test/java/com/tnt/fixture/PtTrainerTraineeFixture.java
  src/test/java/com/tnt/presentation/trainee/TraineeControllerTest.java
  src/test/java/com/tnt/presentation/trainer/TrainerControllerTest.java
Labels: ✅ test, ♻ refactor

#64 [TNT-253] fix: 회원 탈퇴 시 식단 데이터 삭제, 기타 수정
  src/main/java/com/tnt/application/member/WithdrawService.java
  src/main/java/com/tnt/application/pt/PtService.java
  src/main/java/com/tnt/application/trainee/DietService.java
  src/main/java/com/tnt/domain/trainee/Diet.java
  src/main/java/com/tnt/dto/trainer/response/ConnectWithTraineeResponse.java
  src/main/java/com/tnt/infrastructure/mysql/repository/trainee/DietRepository.java
  src/test/java/com/tnt/application/member/WithdrawServiceTest.java
  src/test/java/com/tnt/fixture/PtLessonsFixture.java
  src/test/java/com/tnt/presentation/trainee/TraineeControllerTest.java
Labels: 🐞 bugfix, ✅ test, ♻ refactor
