Repository YAPP-Github/TnT-Server, pull requests merged in 2025-01, with the labels that each got.

#6 [TNT-76] feat: 공통 예외 처리 핸들러 구현
  build.gradle
  src/main/java/com/tnt/global/error/exception/TnTException.java
  src/main/java/com/tnt/global/error/handler/GlobalExceptionHandler.java
  src/main/java/com/tnt/global/error/model/ErrorResponse.java
  src/main/resources/log4j2-local.yml
Labels: ✨ feature, ⚙ setting

#14 [TNT-141] feat: Querydsl 세팅 추가
  .github/PULL_REQUEST_TEMPLATE.md
  build.gradle
  infra/docker-compose-dev.yml
  src/main/java/com/tnt/global/common/util/DynamicQuery.java
  src/main/java/com/tnt/global/config/JpaConfig.java
Labels: 🔧 config, ⚙ setting

#16 [TNT-102] feat: 트레이너 초대 코드 표시 및 재발급 API 구현
  build.gradle
  src/main/java/com/tnt/application/trainer/TrainerService.java
  src/main/java/com/tnt/domain/pt/PtTrainerTrainee.java
  src/main/java/com/tnt/domain/trainer/Trainer.java
  src/main/java/com/tnt/dto/trainer/response/InvitationCodeResponse.java
  src/main/java/com/tnt/global/auth/annotation/AuthMember.java
  src/main/java/com/tnt/global/error/exception/NotFoundException.java
  src/main/java/com/tnt/global/error/exception/OAuthException.java
  src/main/java/com/tnt/global/error/exception/TnTException.java
  src/main/java/com/tnt/global/error/exception/UnauthorizedException.java
  src/main/java/com/tnt/global/error/handler/GlobalExceptionHandler.java
  src/main/java/com/tnt/global/error/model/ErrorMessage.java
  src/main/java/com/tnt/infrastructure/mysql/repository/trainer/TrainerRepository.java
  src/main/java/com/tnt/presentation/trainer/TrainerController.java
  src/main/resources/log4j2-dev.yml
  src/main/resources/log4j2-local.yml
  src/test/java/com/tnt/application/trainer/TrainerServiceTest.java
  src/test/java/com/tnt/presentation/trainer/TrainerControllerTest.java
Labels: ✨ feature, ✅ test, ♻ refactor

#26 [TNT-106] feat: 트레이너 - 트레이니 연결 API 구현
  build.gradle
  gradlew
  infra/docker-compose-dev.yml
  src/main/java/com/tnt/application/auth/SessionService.java
  src/main/java/com/tnt/application/member/MemberService.java
  src/main/java/com/tnt/application/member/NotificationService.java
  src/main/java/com/tnt/application/pt/PtService.java
  src/main/java/com/tnt/application/trainee/TraineeService.java
  src/main/java/com/tnt/application/trainer/TrainerService.java
  src/main/java/com/tnt/domain/pt/PtTrainerTrainee.java
  src/main/java/com/tnt/domain/trainee/Trainee.java
  src/main/java/com/tnt/domain/trainer/Trainer.java
  src/main/java/com/tnt/dto/trainer/ConnectWithTrainerDto.java
  src/main/java/com/tnt/dto/trainer/request/ConnectWithTrainerRequest.java
  src/main/java/com/tnt/dto/trainer/response/ConnectWithTraineeResponse.java
  src/main/java/com/tnt/dto/trainer/response/ConnectWithTrainerResponse.java
  src/main/java/com/tnt/dto/trainer/response/InvitationCodeResponse.java
  src/main/java/com/tnt/dto/trainer/response/InvitationCodeVerifyResponse.java
  src/main/java/com/tnt/global/config/FcmConfig.java
  src/main/java/com/tnt/global/error/model/ErrorMessage.java
  src/main/java/com/tnt/infrastructure/fcm/FcmAdapter.java
  src/main/java/com/tnt/infrastructure/mysql/repository/pt/PtTrainerTraineeRepository.java
  src/main/java/com/tnt/infrastructure/mysql/repository/trainee/PtGoalRepository.java
  src/main/java/com/tnt/infrastructure/mysql/repository/trainee/TraineeRepository.java
  src/main/java/com/tnt/infrastructure/mysql/repository/trainee/TraineeSearchRepository.java
  src/main/java/com/tnt/infrastructure/mysql/repository/trainer/TrainerRepository.java
  src/main/java/com/tnt/infrastructure/mysql/repository/trainer/TrainerSearchRepository.java
  src/main/java/com/tnt/presentation/trainee/TraineeController.java
  src/main/java/com/tnt/presentation/trainer/TrainerController.java
  src/main/resources/log4j2-dev.yml
  src/main/resources/log4j2-prod.yml
  src/test/java/com/tnt/application/member/MemberServiceTest.java
  src/test/java/com/tnt/application/member/NotificationServiceTest.java
  src/test/java/com/tnt/application/pt/PtServiceTest.java
  src/test/java/com/tnt/application/trainee/TraineeServiceTest.java
  src/test/java/com/tnt/application/trainer/TrainerServiceTest.java
  src/test/java/com/tnt/fixture/MemberFixture.java
  src/test/java/com/tnt/fixture/PtTrainerTraineeFixture.java
  src/test/java/com/tnt/presentation/member/MemberControllerTest.java
  src/test/java/com/tnt/presentation/trainee/TraineeControllerTest.java
  src/test/java/com/tnt/presentation/trainer/TrainerControllerTest.java
Labels: ✨ feature, ✅ test

#25 [TNT-160] feat: 로그아웃 기능 구현
  src/main/java/com/tnt/application/auth/CustomOAuth2UserService.java
  src/main/java/com/tnt/application/auth/SessionService.java
  src/main/java/com/tnt/application/member/MemberService.java
  src/main/java/com/tnt/application/member/OAuthService.java
  src/main/java/com/tnt/dto/member/response/LogoutResponse.java
  src/main/java/com/tnt/global/config/SecurityConfig.java
  src/main/java/com/tnt/global/config/WebMvcConfig.java
  src/main/java/com/tnt/global/error/handler/GlobalExceptionHandler.java
  src/main/java/com/tnt/global/error/model/ErrorMessage.java
  src/main/java/com/tnt/presentation/member/AuthenticationController.java
  src/main/java/com/tnt/presentation/member/MemberController.java
  src/test/java/com/tnt/application/auth/SessionServiceTest.java
  src/test/java/com/tnt/application/member/MemberServiceTest.java
  src/test/java/com/tnt/application/member/OAuthServiceTest.java
  src/test/java/com/tnt/presentation/member/AuthenticationControllerTest.java
  src/test/java/com/tnt/presentation/member/MemberControllerTest.java
Labels: ✨ feature

#29 [#28] hotfix: 생일 미저장, push 알림 동의 삭제
  src/main/java/com/tnt/application/member/MemberService.java
  src/main/java/com/tnt/domain/constant/Constant.java
  src/main/java/com/tnt/domain/member/Member.java
  src/main/java/com/tnt/dto/member/request/SignUpRequest.java
  src/main/java/com/tnt/infrastructure/s3/S3Adapter.java
  src/test/java/com/tnt/application/member/MemberServiceTest.java
  src/test/java/com/tnt/application/trainer/TrainerServiceTest.java
  src/test/java/com/tnt/domain/member/MemberIntegrationTest.java
  src/test/java/com/tnt/domain/member/MemberTest.java
  src/test/java/com/tnt/fixture/MemberFixture.java
  src/test/java/com/tnt/infrastructure/s3/S3AdapterTest.java
  src/test/java/com/tnt/presentation/member/MemberControllerTest.java
  src/test/java/com/tnt/presentation/trainer/TrainerControllerTest.java
Labels: 🐞 bugfix

#32 [#31] hotfix: Trainee 주의사항 null 입력 허용
  src/main/java/com/tnt/domain/trainee/Trainee.java
Labels: 🐞 bugfix
